version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Jest-Cucumber Tests
          command: npm test

  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: TypeScript Compile
          command: npx tsc
      - run:
          name: Create artifact directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy compiled output
          command: cp -R dist ~/artifacts || true
      - store_artifacts:
          path: ~/artifacts
          destination: dist

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy step placeholder
          command: "# Replace this with actual deploy script"

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
    # - deploy:
    #     requires:
    #       - build-node
