on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: go to backend
        run: cd ~/backend

      - name: connect and pull
        run: ssh -o StrictHostKeyChecking=no jmc@ssh-pi.2-finger.com "cd ~/backend && git checkout main && git pull"

      - name: cleanup
        run: rm -rf ~/.ssh
