on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: connect and pull
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* jmc@92.168.100.159:/home/jmc/backend/dist
        # run: ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ${{secrets.WORK_DIR}} && git checkout ${{secrets.MAIN_BRANCH}} && git pull"
      # - name: cleanup
      #   run: rm -rf ~/.ssh
